name: Generate rss feeds

on:
  push:
  schedule:
    - cron: "*/15 * * * *"
  workflow_dispatch: 
jobs:
  build:
    name: Run

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.13]


    steps:
    - uses: actions/checkout@v7
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v7
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y wget gnupg
        wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
        echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" | sudo tee /etc/apt/sources.list.d/google-chrome.list
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable
        python -m pip install --upgrade pip
        python -m pip install -r requirements.txt

    - name: Generate rss (safebooru)
      run: |
        python ./safebooru/generate.py
        
    - name: Generate rss (safebooruY)
      env:
        KEY: ${{ secrets.BA }}
        ID: ${{ secrets.BI }}
      run: |
        python ./safebooru/generateY.py
    
    - name: Generate rss (Genshin)
      run: |
        python ./Gen/genshin.py

    - name: Generate rss (NTE)
      run: |
        python ./never/NTE.py
#- name: Generate rss (Safebooru test)
#run: |
#python ./safebooru_test/test.py
    
    - name: Generate rss (air)
      run: |
        python ./notif/generate.py
        
    - name: Generate rss (air)
      run: |
        python ./notif/new1.py
    
    - name: Generate rss (air)
      run: |
        python ./notif/gachagen.py
    
    - uses: stefanzweifel/git-auto-commit-action@v7
      with:
        # Optional but recommended
        # Defaults to "Apply automatic changes"
        commit_message: Apply automatic changes

        file_pattern: ./*.xml

        # Optional local file path to the repository
        # Defaults to the root of the repository
        repository: .

        # Optional: Skip internal call to `git fetch`
        skip_fetch: true
